// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package store

import (
	"context"
)

const checkDatabase = `-- name: CheckDatabase :one
SELECT 1::int as ok
`

func (q *Queries) CheckDatabase(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkDatabase)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
