// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type QboConnection struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	RealmID     string
	CompanyName sql.NullString
	State       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type QboConnectionEvent struct {
	ID              uuid.UUID
	QboConnectionID uuid.UUID
	TenantID        uuid.UUID
	EventType       string
	Message         sql.NullString
	Metadata        json.RawMessage
	OccurredAt      time.Time
}

type QboConnectionToken struct {
	QboConnectionID       uuid.UUID
	TenantID              uuid.UUID
	EncryptedAccessToken  []byte
	EncryptedRefreshToken []byte
	AccessTokenExpiresAt  time.Time
	RefreshTokenExpiresAt sql.NullTime
	TokenType             string
	Scope                 sql.NullString
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
