// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qbo_connections.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createQBOConnection = `-- name: CreateQBOConnection :one
INSERT INTO qbo_connections (
    id,
    tenant_id,
    realm_id,
    company_name,
    state
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, tenant_id, realm_id, company_name, state, created_at, updated_at
`

type CreateQBOConnectionParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	RealmID     string
	CompanyName sql.NullString
	State       string
}

func (q *Queries) CreateQBOConnection(ctx context.Context, arg CreateQBOConnectionParams) (QboConnection, error) {
	row := q.db.QueryRowContext(ctx, createQBOConnection,
		arg.ID,
		arg.TenantID,
		arg.RealmID,
		arg.CompanyName,
		arg.State,
	)
	var i QboConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RealmID,
		&i.CompanyName,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQBOConnectionEvent = `-- name: CreateQBOConnectionEvent :one
INSERT INTO qbo_connection_events (
    id,
    qbo_connection_id,
    tenant_id,
    event_type,
    message,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, qbo_connection_id, tenant_id, event_type, message, metadata, occurred_at
`

type CreateQBOConnectionEventParams struct {
	ID              uuid.UUID
	QboConnectionID uuid.UUID
	TenantID        uuid.UUID
	EventType       string
	Message         sql.NullString
	Metadata        json.RawMessage
}

func (q *Queries) CreateQBOConnectionEvent(ctx context.Context, arg CreateQBOConnectionEventParams) (QboConnectionEvent, error) {
	row := q.db.QueryRowContext(ctx, createQBOConnectionEvent,
		arg.ID,
		arg.QboConnectionID,
		arg.TenantID,
		arg.EventType,
		arg.Message,
		arg.Metadata,
	)
	var i QboConnectionEvent
	err := row.Scan(
		&i.ID,
		&i.QboConnectionID,
		&i.TenantID,
		&i.EventType,
		&i.Message,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const getLatestQBOConnectionEventByType = `-- name: GetLatestQBOConnectionEventByType :one
SELECT id, qbo_connection_id, tenant_id, event_type, message, metadata, occurred_at
FROM qbo_connection_events
WHERE qbo_connection_id = $1
  AND event_type = $2
ORDER BY occurred_at DESC
LIMIT 1
`

type GetLatestQBOConnectionEventByTypeParams struct {
	QboConnectionID uuid.UUID
	EventType       string
}

func (q *Queries) GetLatestQBOConnectionEventByType(ctx context.Context, arg GetLatestQBOConnectionEventByTypeParams) (QboConnectionEvent, error) {
	row := q.db.QueryRowContext(ctx, getLatestQBOConnectionEventByType, arg.QboConnectionID, arg.EventType)
	var i QboConnectionEvent
	err := row.Scan(
		&i.ID,
		&i.QboConnectionID,
		&i.TenantID,
		&i.EventType,
		&i.Message,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const getQBOConnection = `-- name: GetQBOConnection :one
SELECT id, tenant_id, realm_id, company_name, state, created_at, updated_at
FROM qbo_connections
WHERE id = $1
`

func (q *Queries) GetQBOConnection(ctx context.Context, id uuid.UUID) (QboConnection, error) {
	row := q.db.QueryRowContext(ctx, getQBOConnection, id)
	var i QboConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RealmID,
		&i.CompanyName,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQBOConnectionByTenant = `-- name: GetQBOConnectionByTenant :one
SELECT id, tenant_id, realm_id, company_name, state, created_at, updated_at
FROM qbo_connections
WHERE tenant_id = $1
`

func (q *Queries) GetQBOConnectionByTenant(ctx context.Context, tenantID uuid.UUID) (QboConnection, error) {
	row := q.db.QueryRowContext(ctx, getQBOConnectionByTenant, tenantID)
	var i QboConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RealmID,
		&i.CompanyName,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQBOConnectionEvents = `-- name: ListQBOConnectionEvents :many
SELECT id, qbo_connection_id, tenant_id, event_type, message, metadata, occurred_at
FROM qbo_connection_events
WHERE qbo_connection_id = $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListQBOConnectionEvents(ctx context.Context, qboConnectionID uuid.UUID) ([]QboConnectionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listQBOConnectionEvents, qboConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QboConnectionEvent
	for rows.Next() {
		var i QboConnectionEvent
		if err := rows.Scan(
			&i.ID,
			&i.QboConnectionID,
			&i.TenantID,
			&i.EventType,
			&i.Message,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQBOConnectionEventsByTenant = `-- name: ListQBOConnectionEventsByTenant :many
SELECT id, qbo_connection_id, tenant_id, event_type, message, metadata, occurred_at
FROM qbo_connection_events
WHERE tenant_id = $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListQBOConnectionEventsByTenant(ctx context.Context, tenantID uuid.UUID) ([]QboConnectionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listQBOConnectionEventsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QboConnectionEvent
	for rows.Next() {
		var i QboConnectionEvent
		if err := rows.Scan(
			&i.ID,
			&i.QboConnectionID,
			&i.TenantID,
			&i.EventType,
			&i.Message,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQBOConnectionCompanyName = `-- name: UpdateQBOConnectionCompanyName :one
UPDATE qbo_connections
SET
    company_name = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, realm_id, company_name, state, created_at, updated_at
`

type UpdateQBOConnectionCompanyNameParams struct {
	ID          uuid.UUID
	CompanyName sql.NullString
}

func (q *Queries) UpdateQBOConnectionCompanyName(ctx context.Context, arg UpdateQBOConnectionCompanyNameParams) (QboConnection, error) {
	row := q.db.QueryRowContext(ctx, updateQBOConnectionCompanyName, arg.ID, arg.CompanyName)
	var i QboConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RealmID,
		&i.CompanyName,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQBOConnectionState = `-- name: UpdateQBOConnectionState :one
UPDATE qbo_connections
SET
    state = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, realm_id, company_name, state, created_at, updated_at
`

type UpdateQBOConnectionStateParams struct {
	ID    uuid.UUID
	State string
}

func (q *Queries) UpdateQBOConnectionState(ctx context.Context, arg UpdateQBOConnectionStateParams) (QboConnection, error) {
	row := q.db.QueryRowContext(ctx, updateQBOConnectionState, arg.ID, arg.State)
	var i QboConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RealmID,
		&i.CompanyName,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
