// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qbo_connection_tokens.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getQBOConnectionTokens = `-- name: GetQBOConnectionTokens :one
SELECT qbo_connection_id, tenant_id, encrypted_access_token, encrypted_refresh_token, access_token_expires_at, refresh_token_expires_at, token_type, scope, version, created_at, updated_at
FROM qbo_connection_tokens
WHERE qbo_connection_id = $1
`

func (q *Queries) GetQBOConnectionTokens(ctx context.Context, qboConnectionID uuid.UUID) (QboConnectionToken, error) {
	row := q.db.QueryRowContext(ctx, getQBOConnectionTokens, qboConnectionID)
	var i QboConnectionToken
	err := row.Scan(
		&i.QboConnectionID,
		&i.TenantID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.TokenType,
		&i.Scope,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQBOConnectionTokensForUpdate = `-- name: GetQBOConnectionTokensForUpdate :one
SELECT qbo_connection_id, tenant_id, encrypted_access_token, encrypted_refresh_token, access_token_expires_at, refresh_token_expires_at, token_type, scope, version, created_at, updated_at
FROM qbo_connection_tokens
WHERE qbo_connection_id = $1
FOR UPDATE
`

func (q *Queries) GetQBOConnectionTokensForUpdate(ctx context.Context, qboConnectionID uuid.UUID) (QboConnectionToken, error) {
	row := q.db.QueryRowContext(ctx, getQBOConnectionTokensForUpdate, qboConnectionID)
	var i QboConnectionToken
	err := row.Scan(
		&i.QboConnectionID,
		&i.TenantID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.TokenType,
		&i.Scope,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceQBOConnectionTokensIfVersion = `-- name: ReplaceQBOConnectionTokensIfVersion :one
UPDATE qbo_connection_tokens
SET
    encrypted_access_token = $3,
    encrypted_refresh_token = $4,
    access_token_expires_at = $5,
    refresh_token_expires_at = $6,
    token_type = $7,
    scope = $8,
    version = version + 1,
    updated_at = now()
WHERE qbo_connection_id = $1
  AND version = $2
RETURNING qbo_connection_id, tenant_id, encrypted_access_token, encrypted_refresh_token, access_token_expires_at, refresh_token_expires_at, token_type, scope, version, created_at, updated_at
`

type ReplaceQBOConnectionTokensIfVersionParams struct {
	QboConnectionID       uuid.UUID
	Version               int64
	EncryptedAccessToken  []byte
	EncryptedRefreshToken []byte
	AccessTokenExpiresAt  time.Time
	RefreshTokenExpiresAt sql.NullTime
	TokenType             string
	Scope                 sql.NullString
}

func (q *Queries) ReplaceQBOConnectionTokensIfVersion(ctx context.Context, arg ReplaceQBOConnectionTokensIfVersionParams) (QboConnectionToken, error) {
	row := q.db.QueryRowContext(ctx, replaceQBOConnectionTokensIfVersion,
		arg.QboConnectionID,
		arg.Version,
		arg.EncryptedAccessToken,
		arg.EncryptedRefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.TokenType,
		arg.Scope,
	)
	var i QboConnectionToken
	err := row.Scan(
		&i.QboConnectionID,
		&i.TenantID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.TokenType,
		&i.Scope,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertQBOConnectionTokens = `-- name: UpsertQBOConnectionTokens :one
INSERT INTO qbo_connection_tokens (
    qbo_connection_id,
    tenant_id,
    encrypted_access_token,
    encrypted_refresh_token,
    access_token_expires_at,
    refresh_token_expires_at,
    token_type,
    scope
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (qbo_connection_id) DO UPDATE
SET
    encrypted_access_token = EXCLUDED.encrypted_access_token,
    encrypted_refresh_token = EXCLUDED.encrypted_refresh_token,
    access_token_expires_at = EXCLUDED.access_token_expires_at,
    refresh_token_expires_at = EXCLUDED.refresh_token_expires_at,
    token_type = EXCLUDED.token_type,
    scope = EXCLUDED.scope,
    version = qbo_connection_tokens.version + 1,
    updated_at = now()
RETURNING qbo_connection_id, tenant_id, encrypted_access_token, encrypted_refresh_token, access_token_expires_at, refresh_token_expires_at, token_type, scope, version, created_at, updated_at
`

type UpsertQBOConnectionTokensParams struct {
	QboConnectionID       uuid.UUID
	TenantID              uuid.UUID
	EncryptedAccessToken  []byte
	EncryptedRefreshToken []byte
	AccessTokenExpiresAt  time.Time
	RefreshTokenExpiresAt sql.NullTime
	TokenType             string
	Scope                 sql.NullString
}

func (q *Queries) UpsertQBOConnectionTokens(ctx context.Context, arg UpsertQBOConnectionTokensParams) (QboConnectionToken, error) {
	row := q.db.QueryRowContext(ctx, upsertQBOConnectionTokens,
		arg.QboConnectionID,
		arg.TenantID,
		arg.EncryptedAccessToken,
		arg.EncryptedRefreshToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.TokenType,
		arg.Scope,
	)
	var i QboConnectionToken
	err := row.Scan(
		&i.QboConnectionID,
		&i.TenantID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.TokenType,
		&i.Scope,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
