// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qbo_oauth_states.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeOAuthState = `-- name: ConsumeOAuthState :one
UPDATE qbo_oauth_states
SET consumed_at = now()
WHERE id = $1
  AND consumed_at IS NULL
RETURNING id
`

func (q *Queries) ConsumeOAuthState(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, consumeOAuthState, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const createOAuthState = `-- name: CreateOAuthState :one
INSERT INTO qbo_oauth_states (
    id,
    tenant_id,
    state_checksum,
    encrypted_state,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tenant_id, state_checksum, encrypted_state, expires_at, consumed_at, created_at
`

type CreateOAuthStateParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	StateChecksum  string
	EncryptedState []byte
	ExpiresAt      time.Time
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) (QboOauthState, error) {
	row := q.db.QueryRowContext(ctx, createOAuthState,
		arg.ID,
		arg.TenantID,
		arg.StateChecksum,
		arg.EncryptedState,
		arg.ExpiresAt,
	)
	var i QboOauthState
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StateChecksum,
		&i.EncryptedState,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :exec
DELETE FROM qbo_oauth_states
WHERE expires_at < now()
  AND consumed_at IS NULL
`

func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOAuthStates)
	return err
}

const getActiveOAuthStateByChecksum = `-- name: GetActiveOAuthStateByChecksum :one
SELECT id, tenant_id, state_checksum, encrypted_state, expires_at, consumed_at, created_at
FROM qbo_oauth_states
WHERE state_checksum = $1
  AND consumed_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetActiveOAuthStateByChecksum(ctx context.Context, stateChecksum string) (QboOauthState, error) {
	row := q.db.QueryRowContext(ctx, getActiveOAuthStateByChecksum, stateChecksum)
	var i QboOauthState
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StateChecksum,
		&i.EncryptedState,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
